version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    ports:
      - '0.0.0.0:${PORT}:${PORT}'
    networks:
      - kszinhu
    env_file:
      - .env

networks:
  kszinhu:
    name: kszinhu
    external: true
