version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-client
    restart: unless-stopped
    ports:
      - '0.0.0.0:${PORT}:${PORT}'
    env_file:
      - .env
