version: "3.8"
services:
  client:
    container_name: kszinhu.portfolio-client
    image: kszinhu/portfolio-client:latest
    restart: unless-stopped
    ports:
      - '0.0.0.0:${PORT}:${PORT}'
    networks:
      - kszinhu
    env_file:
      - stack.env

networks:
  kszinhu:
    name: kszinhu
    external: true
