service: new_kszinhu_dev

image: kszinhu/new_kszinhu_dev

servers:
  web:
    hosts:
      - 216.144.226.237
    labels:
      traefik.enable: "true"
      traefik.http.routers.new_kszinhu_dev.rule: "Host(`kszinhu.dev`) || Host(`www.kszinhu.dev`)"
      traefik.http.routers.new_kszinhu_dev.entrypoints: "websecure"
      traefik.http.routers.new_kszinhu_dev.tls.certresolver: "letsencrypt"
      traefik.http.services.new_kszinhu_dev.loadbalancer.server.port: "80"
    options:
      network: "traefik"

proxy:
  host: false

registry:
  server: ghcr.io
  username: kszinhu
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_LOG_LEVEL: info

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "new_kszinhu_dev_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
  remote: ssh://kszinhu@216.144.226.237

ssh:
  user: kszinhu
