name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  lint_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint Ruby code for consistent style
        run: bin/rubocop -f github

  lint_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint JavaScript/TypeScript with Biome
        run: yarn biome check .

  test_backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request' && (
      contains(github.event.pull_request.changed_files, 'app/views/') == false &&
      contains(github.event.pull_request.changed_files, 'app/frontend/') == false &&
      !endsWith(github.event.pull_request.changed_files, '.tsx') &&
      !endsWith(github.event.pull_request.changed_files, '.ts') &&
      !endsWith(github.event.pull_request.changed_files, '.css')
      )
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile

      - name: Run backend tests
        env:
          RAILS_ENV: test
          # REDIS_URL: redis://localhost:6379/0
        run: |
          if [ -f db/schema.rb ]; then
            bundle exec rails db:test:prepare
          else
            echo "db/schema.rb not found, skipping db:test:prepare"
          fi
          bundle exec rspec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore

  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile

      - name: Run frontend tests
        run: yarn coverage
